name = "pixel-ai-starter"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

# 静态资源目录
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[observability]
enabled = true
